version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Packer"
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install packer
  build:
    commands:
      - cd ami_build_packer
      - ./packer build -color=false images/web_ami_image.json | tee build.log
  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
      # Packer doesn't return non-zero status; we must do that if Packer build failed
      - test -s ami_id.txt || exit 1
      - cat ami_id.txt
artifacts:
  files:
    - build.log
  discard-paths: yes